services:
  - type: web
    name: travel-planner-backend-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3019

  - type: static
    name: travel-planner-frontend
    env: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://travel-planner-backend-api.onrender.com/api/*
